src/App/Exception/DbException.php, src/App/Repository/FrameworkRepository.php
@mattbstudio24 please can you review & approve the code. I am testing this on Dev & PreProd first & won't merge into master until we are ready to deploy.
@MariaS24 it's useful to review these changes, actual fix is line 301, I've added some more defensive coding to the DB saving to pick up on these sort of errors in the future.
=> Update publish_on_website to 1 or 0, add DbException

composer.json, composer.lock, public/wp-content/plugins/ccs-salesforce/includes/cli-commands.php
Fixes:
WP CLI Errors will no longer stop the import process running. 
DB connection object is no longer duplicated and uses the class version on the import class.
=> Import interuption fixes

deploy/import/files/wp_import
Change CRON times and add Curl for Dead mans snitch
=> Add dead mans snitch for testing

docs/CONTINUOUS_INTEGRATION.md, docs/IMPORT_CLI_COMMANDS.md, docs/INSTALL.md, docs/README.md, docs/SALESFORCE_DATA_SYNC.md
Updated and added Docs from ccsweb-docs
=> Updated and added Docs

public/wp-content/plugins/fewbricks_definitions/bricks/component-free-text.php
Added cta button to the free text component
=> Modified free text text box

public/wp-content/plugins/ccs-salesforce/includes/wp-rest-api/CustomFrameworkApi.php
added a filter for framework's expected_live_date
=> framework expected_live_date is past will not show

docs/Important information.md, docs/Known issues.md, docs/PC setup.md, public/wp-content/plugins/fewbricks_definitions/bricks/inline-contact-form.php
These changes are in dev but not merged correctly into preprod.
=> Apply changes that have diverged in dev manually to preprod

docs/SALESFORCE_DATA_SYNC.md, public/search-api/frameworks.php, public/wp-content/plugins/ccs-salesforce/includes/cli-commands.php
* when filter for Energy, U&F will also show (#122)
* deleting lot on saleforce will now delete local data too
* updated docs
=> BAU release 3

public/wp-content/themes/ccs/package-lock.json
Reverts Crown-Commercial-Service/ccs-wordpress#130
=> Revert "update for Dependabot"

.gitignore, docs/SALESFORCE_DATA_SYNC.md, docs/USER_ROLES.md, public/search-api/frameworks.php, public/wp-content/plugins/ccs-salesforce/includes/cli-commands.php, public/wp-content/plugins/ccs-salesforce/includes/wp-rest-api/CustomFrameworkApi.php, public/wp-content/themes/ccs/package-lock.json, src/App/Config/Mappings/Lot.yaml, src/App/Model/Lot.php, src/App/Services/Salesforce/SalesforceApi.php
Changes for tickets WEB-1405 and WEB-1424.
WEB-1405: Supplier listed more than once on same framework 
WEB-1424: Removing repeated code related to the hideLot field
=> dev into preprod

.gitignore, docs/SALESFORCE_DATA_SYNC.md, docs/USER_ROLES.md, public/search-api/frameworks.php, public/wp-content/plugins/ccs-salesforce/includes/cli-commands.php, public/wp-content/plugins/ccs-salesforce/includes/wp-rest-api/CustomFrameworkApi.php, public/wp-content/themes/ccs/package-lock.json, src/App/Config/Mappings/Lot.yaml, src/App/Model/Lot.php, src/App/Services/Salesforce/SalesforceApi.php
- [WEB-1405](https://crowncommercialservice.atlassian.net/browse/WEB-1405) Framework supplier that supplies different lots for the same framework will no longer show up multiple time
=> Preprod into master

public/wp-content/plugins/ccs-custom/library/options-page.php, public/wp-content/plugins/ccs-salesforce/ccs-salesforce-import.php, public/wp-content/plugins/ccs-salesforce/includes/wp-rest-api/CustomUpcomingDealsApi.php
To test the API is working you will need add the following custom fields first:
**Title of field group: Upcoming Deals Page**
1. **Field Label**: Upcoming Deals
**Field name**: upcoming_deals
**Field Type**: Repeater
**Sub Fields:** Title (Field name: title) (Type: **Text**), 
Page Description(Field name: page_description) (Type: Wysiwyg Editor)
**Maximum row**: 1
**Layout** Block
2. **Field Label**: Table 0
**Field name**: table_0
**Field Type**: Repeater
**Sub Fields:** Title (Field name: title) (Type: **Text**)
**Maximum row**: 1
**Layout** Block
3. **Field Label**: Table 1
**Field name**: table_1
**Field Type**: Repeater
**Sub Fields:** Title (Field name: title) (Type: **Text**), 
Caption(Field name: caption) (Type:Text Area)
**Maximum row**: 1
**Layout** Block
4. **Field Label**: …
=> Web 1449 remove hardcoding upcoming deals

public/wp-content/plugins/ccs-salesforce/includes/cli-commands.php, public/wp-content/plugins/ccs-salesforce/includes/wp-rest-api/CustomSupplierApi.php
- stop supplier that is only supplier for DPS framework from showing on supplier result page
- stop DPS framework from showing on the supplier show page
- corrected the method decorator so that it matches the documentation
=> WEB-1461-remove-supplier-that-only-supply-dps-from-result

docs/ELASTICSEARCH.md
Pulls information from Frontend elasticsearch doc to combine into 1 doucmenation on Wordpress
=> Combine Elasticsearch Documenation from Frontend

public/wp-content/plugins/ccs-salesforce/includes/wp-rest-api/CustomHomepageComponentsApi.php
Reverts Crown-Commercial-Service/ccs-wordpress#167
=> Revert "Web 1479 upcoming deal issue"

public/wp-content/plugins/ccs-salesforce/includes/cli-commands.php, src/App/Search/AbstractSearchClient.php
Reverts Crown-Commercial-Service/ccs-wordpress#175
=> Revert " Web 1471 add stop words"

public/wp-content/plugins/ccs-salesforce/includes/cli-commands.php, src/App/Search/AbstractSearchClient.php
Reverts Crown-Commercial-Service/ccs-wordpress#181
=> Revert "Web 1471 stopwords and reindex"

public/wp-content/themes/ccs/functions.php, public/wp-includes/rest-api/class-wp-rest-server.php
by adding a check before the forloop in api-rest-server
=> fixed api endpoint for wp/v2/event

public/wp-content/themes/ccs/package-lock.json
Reverts Crown-Commercial-Service/ccs-wordpress#228
=> Revert "Update/dependabot"

public/wp-content/plugins/ccs-custom/ccs-custom.php, public/wp-content/plugins/ccs-custom/library/rest-api/rest-api-news-navigation.php, public/wp-content/themes/ccs/functions.php
- moditfy post endpoint to add news navigation detail
- newly uploaded media will not be attach to any post
=> DEV to UAT

public/wp-content/plugins/ccs-custom/ccs-custom.php, public/wp-content/plugins/ccs-custom/library/rest-api/rest-api-news-navigation.php, src/App/Repository/LotRepository.php
- WEB-1547- No longer import one lot per import process
- WEB-1548- Previous / Next Article news navigation (API changes) (Not used in frontend as waiting for design)
=> PROD Deployment 

public/wp-content/themes/ccs/functions.php
Reverts Crown-Commercial-Service/ccs-wordpress#303
=> Revert "adding Access Control Headers for API"

public/wp-content/themes/ccs/functions.php
pages will now should hidden content in the same tax_query
=> Deployment 14/07/22

public/wp-content/plugins/ccs-salesforce/includes/cli-commands.php, src/App/Services/OpGenie/OpGenieLogger.php, src/App/Services/Salesforce/SalesforceApi.php
@zubairali6 This ticket cannot be test on DEV and UAT, please test this on your local by removing the second half of the condidtion in **cli-commands.php line 1251.**
=> Web 2071 event cron job alert

public/wp-content/plugins/fewbricks_definitions/bricks/component-accordion.php, public/wp-content/plugins/fewbricks_definitions/field-groups/post-types/cas-framework.php, public/wp-content/themes/ccs/functions.php
WEB-2361: Filter function on news page without JS
=> Deployment 24/08

public/wp-content/themes/ccs/functions.php
This reverts commit dec6814e21194585f248f979f1440c0bad4ea14e.
=> Revert "Test Malicous upload functionality"

src/App/Search/FrameworkSearchClient.php
Reverts Crown-Commercial-Service/ccs-wordpress#619
=> Revert "Remove fuzzines for multiple fields"

public/wp-content/themes/ccs/package-lock.json
Reverts Crown-Commercial-Service/ccs-wordpress#623
=> Revert "Bump braces from 3.0.2 to 3.0.3 in /public/wp-content/themes/ccs"

public/wp-config.php, public/wp-content/plugins/ccs-salesforce/includes/cli-commands.php, public/wp-content/plugins/ccs-salesforce/includes/wp-rest-api/CustomFrameworkApi.php, src/App/Config/Mappings/Framework.yaml, src/App/Model/Framework.php, src/App/Repository/FrameworkRepository.php
[WEB-2974](https://crowncommercialservice.atlassian.net/browse/WEB-2974)
[WEB-2974]: https://crowncommercialservice.atlassian.net/browse/WEB-2974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Web 2974 crp compliance statement display on agreements

.gitignore, public/wp-content/plugins/fewbricks_definitions/field-groups/post-types/event.php
[WEB-2937](https://crowncommercialservice.atlassian.net/browse/WEB-2937)
[WEB-2937]: https://crowncommercialservice.atlassian.net/browse/WEB-2937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> added event summary textbox

.gitignore, public/wp-content/plugins/ccs-custom/ccs-custom.php, public/wp-content/plugins/ccs-custom/library/logger.php
[WEB-3096](https://crowncommercialservice.atlassian.net/browse/WEB-3096)
[WEB-3096]: https://crowncommercialservice.atlassian.net/browse/WEB-3096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> added a custom user activity logger on wordpress

public/wp-content/plugins/fewbricks/lib/fewbricks.php, public/wp-content/plugins/fewbricks_definitions/field-groups/templates/page.php, public/wp-includes/l10n.php
[WEB-3109](https://crowncommercialservice.atlassian.net/browse/WEB-3109)
[WEB-3109]: https://crowncommercialservice.atlassian.net/browse/WEB-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Web 3109 assisted procurement add in contact form link
